// Mocks generated by Mockito from annotations
// in taskle_app/test/features/auth/auth_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;
import 'dart:ui' as _i14;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:taskle_app/src/common/patterns/result_pattern.dart' as _i8;
import 'package:taskle_app/src/common/patterns/state_pattern.dart' as _i13;
import 'package:taskle_app/src/common/services/connection_service.dart' as _i3;
import 'package:taskle_app/src/common/services/http_service.dart' as _i5;
import 'package:taskle_app/src/common/services/storage_service.dart' as _i6;
import 'package:taskle_app/src/features/auth/exceptions/auth_exception.dart'
    as _i10;
import 'package:taskle_app/src/features/auth/models/auth_model.dart' as _i9;
import 'package:taskle_app/src/features/auth/models/auth_session_model.dart'
    as _i2;
import 'package:taskle_app/src/features/auth/repositories/auth_repository.dart'
    as _i7;
import 'package:taskle_app/src/features/auth/view_models/auth_session_view_model.dart'
    as _i16;
import 'package:taskle_app/src/features/auth/view_models/login_view_model.dart'
    as _i12;
import 'package:taskle_app/src/features/auth/view_models/register_view_model.dart'
    as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthSessionModel_0 extends _i1.SmartFake
    implements _i2.AuthSessionModel {
  _FakeAuthSessionModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ConnectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionService extends _i1.Mock implements _i3.ConnectionService {
  MockConnectionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i4.Future<void> checkConnection() => (super.noSuchMethod(
    Invocation.method(#checkConnection, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);
}

/// A class which mocks [HttpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpService extends _i1.Mock implements _i5.HttpService {
  MockHttpService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<({Object? data, String? error, int? statusCode})> getData({
    required String? path,
  }) => (super.noSuchMethod(
    Invocation.method(#getData, [], {#path: path}),
    returnValue:
        _i4.Future<({Object? data, String? error, int? statusCode})>.value((
          data: null,
          error: null,
          statusCode: null,
        )),
  ) as _i4.Future<({Object? data, String? error, int? statusCode})>);

  @override
  _i4.Future<({Object? data, String? error, int? statusCode})> postData({
    required String? path,
    required Map<String, dynamic>? body,
  }) => (super.noSuchMethod(
    Invocation.method(#postData, [], {#path: path, #body: body}),
    returnValue:
        _i4.Future<({Object? data, String? error, int? statusCode})>.value((
          data: null,
          error: null,
          statusCode: null,
        )),
  ) as _i4.Future<({Object? data, String? error, int? statusCode})>);

  @override
  _i4.Future<({Object? data, String? error, int? statusCode})> putData({
    required String? path,
    required Map<String, dynamic>? body,
  }) => (super.noSuchMethod(
    Invocation.method(#putData, [], {#path: path, #body: body}),
    returnValue:
        _i4.Future<({Object? data, String? error, int? statusCode})>.value((
          data: null,
          error: null,
          statusCode: null,
        )),
  ) as _i4.Future<({Object? data, String? error, int? statusCode})>);

  @override
  _i4.Future<({Object? data, String? error, int? statusCode})> deleteData({
    required String? path,
  }) => (super.noSuchMethod(
    Invocation.method(#deleteData, [], {#path: path}),
    returnValue:
        _i4.Future<({Object? data, String? error, int? statusCode})>.value((
          data: null,
          error: null,
          statusCode: null,
        )),
  ) as _i4.Future<({Object? data, String? error, int? statusCode})>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i6.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initStorage() => (super.noSuchMethod(
    Invocation.method(#initStorage, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  bool? getBoolValueSync({required String? key}) =>
      (super.noSuchMethod(Invocation.method(#getBoolValueSync, [], {#key: key}))
          as bool?);

  @override
  _i4.Future<bool?> getBoolValue({required String? key}) => (super.noSuchMethod(
    Invocation.method(#getBoolValue, [], {#key: key}),
    returnValue: _i4.Future<bool?>.value(),
  ) as _i4.Future<bool?>);

  @override
  _i4.Future<void> setBoolValue({required String? key, required bool? value}) =>
      (super.noSuchMethod(
        Invocation.method(#setBoolValue, [], {#key: key, #value: value}),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String? getStringValueSync({required String? key}) => (super.noSuchMethod(
    Invocation.method(#getStringValueSync, [], {#key: key}),
  ) as String?);

  @override
  _i4.Future<String?> getStringValue({required String? key}) =>
      (super.noSuchMethod(
        Invocation.method(#getStringValue, [], {#key: key}),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> setStringValue({
    required String? key,
    required String? value,
  }) => (super.noSuchMethod(
    Invocation.method(#setStringValue, [], {#key: key, #value: value}),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeValue({required String? key}) => (super.noSuchMethod(
    Invocation.method(#removeValue, [], {#key: key}),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearStorage() => (super.noSuchMethod(
    Invocation.method(#clearStorage, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i7.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i8.ResultPattern<_i9.AuthModel, _i10.AuthException>> register({
    required String? name,
    required String? email,
    required String? password,
  }) => (super.noSuchMethod(
    Invocation.method(#register, [], {
      #name: name,
      #email: email,
      #password: password,
    }),
    returnValue:
        _i4.Future<_i8.ResultPattern<_i9.AuthModel, _i10.AuthException>>.value(
          _i11.dummyValue<_i8.ResultPattern<_i9.AuthModel, _i10.AuthException>>(
            this,
            Invocation.method(#register, [], {
              #name: name,
              #email: email,
              #password: password,
            }),
          ),
        ),
  ) as _i4.Future<_i8.ResultPattern<_i9.AuthModel, _i10.AuthException>>);

  @override
  _i4.Future<_i8.ResultPattern<_i9.AuthModel, _i10.AuthException>> login({
    required String? email,
    required String? password,
  }) => (super.noSuchMethod(
    Invocation.method(#login, [], {#email: email, #password: password}),
    returnValue:
        _i4.Future<_i8.ResultPattern<_i9.AuthModel, _i10.AuthException>>.value(
          _i11.dummyValue<_i8.ResultPattern<_i9.AuthModel, _i10.AuthException>>(
            this,
            Invocation.method(#login, [], {#email: email, #password: password}),
          ),
        ),
  ) as _i4.Future<_i8.ResultPattern<_i9.AuthModel, _i10.AuthException>>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
    Invocation.method(#logout, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<bool> hasSession() => (super.noSuchMethod(
    Invocation.method(#hasSession, []),
    returnValue: _i4.Future<bool>.value(false),
  ) as _i4.Future<bool>);
}

/// A class which mocks [LoginViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginViewModel extends _i1.Mock implements _i12.LoginViewModel {
  MockLoginViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.StatePattern<_i9.AuthModel, _i10.AuthException> get state =>
      (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i11
            .dummyValue<_i13.StatePattern<_i9.AuthModel, _i10.AuthException>>(
              this,
              Invocation.getter(#state),
            ),
      ) as _i13.StatePattern<_i9.AuthModel, _i10.AuthException>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> login({required String? email, required String? password}) =>
      (super.noSuchMethod(
        Invocation.method(#login, [], {#email: email, #password: password}),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i13.StatePattern<_i9.AuthModel, _i10.AuthException> build() =>
      (super.noSuchMethod(
        Invocation.method(#build, []),
        returnValue: _i11
            .dummyValue<_i13.StatePattern<_i9.AuthModel, _i10.AuthException>>(
              this,
              Invocation.method(#build, []),
            ),
      ) as _i13.StatePattern<_i9.AuthModel, _i10.AuthException>);

  @override
  void emitState(
    _i13.StatePattern<_i9.AuthModel, _i10.AuthException>? newState,
  ) => super.noSuchMethod(
    Invocation.method(#emitState, [newState]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [RegisterViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterViewModel extends _i1.Mock implements _i15.RegisterViewModel {
  MockRegisterViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.StatePattern<_i9.AuthModel, _i10.AuthException> get state =>
      (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i11
            .dummyValue<_i13.StatePattern<_i9.AuthModel, _i10.AuthException>>(
              this,
              Invocation.getter(#state),
            ),
      ) as _i13.StatePattern<_i9.AuthModel, _i10.AuthException>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> register({
    required String? name,
    required String? email,
    required String? password,
  }) => (super.noSuchMethod(
    Invocation.method(#register, [], {
      #name: name,
      #email: email,
      #password: password,
    }),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i13.StatePattern<_i9.AuthModel, _i10.AuthException> build() =>
      (super.noSuchMethod(
        Invocation.method(#build, []),
        returnValue: _i11
            .dummyValue<_i13.StatePattern<_i9.AuthModel, _i10.AuthException>>(
              this,
              Invocation.method(#build, []),
            ),
      ) as _i13.StatePattern<_i9.AuthModel, _i10.AuthException>);

  @override
  void emitState(
    _i13.StatePattern<_i9.AuthModel, _i10.AuthException>? newState,
  ) => super.noSuchMethod(
    Invocation.method(#emitState, [newState]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthSessionViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthSessionViewModel extends _i1.Mock
    implements _i16.AuthSessionViewModel {
  MockAuthSessionViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthSessionModel get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _FakeAuthSessionModel_0(this, Invocation.getter(#state)),
  ) as _i2.AuthSessionModel);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> checkSession() => (super.noSuchMethod(
    Invocation.method(#checkSession, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
    Invocation.method(#logout, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i2.AuthSessionModel build() => (super.noSuchMethod(
    Invocation.method(#build, []),
    returnValue: _FakeAuthSessionModel_0(this, Invocation.method(#build, [])),
  ) as _i2.AuthSessionModel);

  @override
  void emitState(_i2.AuthSessionModel? newState) => super.noSuchMethod(
    Invocation.method(#emitState, [newState]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
