// Mocks generated by Mockito from annotations
// in taskle_app/test/features/tasks/task_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;
import 'dart:ui' as _i13;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:taskle_app/src/common/patterns/result_pattern.dart' as _i7;
import 'package:taskle_app/src/common/services/connection_service.dart' as _i3;
import 'package:taskle_app/src/common/services/http_service.dart' as _i5;
import 'package:taskle_app/src/features/tasks/exceptions/task_exception.dart'
    as _i9;
import 'package:taskle_app/src/features/tasks/models/deleted_task_model.dart'
    as _i11;
import 'package:taskle_app/src/features/tasks/models/task_model.dart' as _i8;
import 'package:taskle_app/src/features/tasks/models/task_screen_state.dart'
    as _i2;
import 'package:taskle_app/src/features/tasks/repositories/task_repository.dart'
    as _i6;
import 'package:taskle_app/src/features/tasks/view_models/task_view_model.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTaskScreenState_0 extends _i1.SmartFake
    implements _i2.TaskScreenState {
  _FakeTaskScreenState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ConnectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionService extends _i1.Mock implements _i3.ConnectionService {
  MockConnectionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i4.Future<void> checkConnection() => (super.noSuchMethod(
    Invocation.method(#checkConnection, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);
}

/// A class which mocks [HttpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpService extends _i1.Mock implements _i5.HttpService {
  MockHttpService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<({Object? data, String? error, int? statusCode})> getData({
    required String? path,
  }) => (super.noSuchMethod(
    Invocation.method(#getData, [], {#path: path}),
    returnValue:
        _i4.Future<({Object? data, String? error, int? statusCode})>.value((
          data: null,
          error: null,
          statusCode: null,
        )),
  ) as _i4.Future<({Object? data, String? error, int? statusCode})>);

  @override
  _i4.Future<({Object? data, String? error, int? statusCode})> postData({
    required String? path,
    required Map<String, dynamic>? body,
  }) => (super.noSuchMethod(
    Invocation.method(#postData, [], {#path: path, #body: body}),
    returnValue:
        _i4.Future<({Object? data, String? error, int? statusCode})>.value((
          data: null,
          error: null,
          statusCode: null,
        )),
  ) as _i4.Future<({Object? data, String? error, int? statusCode})>);

  @override
  _i4.Future<({Object? data, String? error, int? statusCode})> putData({
    required String? path,
    required Map<String, dynamic>? body,
  }) => (super.noSuchMethod(
    Invocation.method(#putData, [], {#path: path, #body: body}),
    returnValue:
        _i4.Future<({Object? data, String? error, int? statusCode})>.value((
          data: null,
          error: null,
          statusCode: null,
        )),
  ) as _i4.Future<({Object? data, String? error, int? statusCode})>);

  @override
  _i4.Future<({Object? data, String? error, int? statusCode})> deleteData({
    required String? path,
  }) => (super.noSuchMethod(
    Invocation.method(#deleteData, [], {#path: path}),
    returnValue:
        _i4.Future<({Object? data, String? error, int? statusCode})>.value((
          data: null,
          error: null,
          statusCode: null,
        )),
  ) as _i4.Future<({Object? data, String? error, int? statusCode})>);
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i6.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i7.ResultPattern<List<_i8.TaskModel>, _i9.TaskException>>
  findAllTasks() => (super.noSuchMethod(
    Invocation.method(#findAllTasks, []),
    returnValue:
        _i4.Future<
          _i7.ResultPattern<List<_i8.TaskModel>, _i9.TaskException>
        >.value(
          _i10.dummyValue<
            _i7.ResultPattern<List<_i8.TaskModel>, _i9.TaskException>
          >(this, Invocation.method(#findAllTasks, [])),
        ),
  ) as _i4.Future<_i7.ResultPattern<List<_i8.TaskModel>, _i9.TaskException>>);

  @override
  _i4.Future<_i7.ResultPattern<_i8.TaskModel, _i9.TaskException>> createTask({
    required String? title,
    required String? content,
  }) => (super.noSuchMethod(
    Invocation.method(#createTask, [], {#title: title, #content: content}),
    returnValue:
        _i4.Future<_i7.ResultPattern<_i8.TaskModel, _i9.TaskException>>.value(
          _i10.dummyValue<_i7.ResultPattern<_i8.TaskModel, _i9.TaskException>>(
            this,
            Invocation.method(#createTask, [], {
              #title: title,
              #content: content,
            }),
          ),
        ),
  ) as _i4.Future<_i7.ResultPattern<_i8.TaskModel, _i9.TaskException>>);

  @override
  _i4.Future<_i7.ResultPattern<_i8.TaskModel, _i9.TaskException>> updateTask({
    required int? id,
    required String? title,
    required String? content,
    required bool? isCompleted,
  }) => (super.noSuchMethod(
    Invocation.method(#updateTask, [], {
      #id: id,
      #title: title,
      #content: content,
      #isCompleted: isCompleted,
    }),
    returnValue:
        _i4.Future<_i7.ResultPattern<_i8.TaskModel, _i9.TaskException>>.value(
          _i10.dummyValue<_i7.ResultPattern<_i8.TaskModel, _i9.TaskException>>(
            this,
            Invocation.method(#updateTask, [], {
              #id: id,
              #title: title,
              #content: content,
              #isCompleted: isCompleted,
            }),
          ),
        ),
  ) as _i4.Future<_i7.ResultPattern<_i8.TaskModel, _i9.TaskException>>);

  @override
  _i4.Future<_i7.ResultPattern<_i11.DeletedTaskModel, _i9.TaskException>>
  deleteTask(int? id) => (super.noSuchMethod(
    Invocation.method(#deleteTask, [id]),
    returnValue:
        _i4.Future<
          _i7.ResultPattern<_i11.DeletedTaskModel, _i9.TaskException>
        >.value(
          _i10.dummyValue<
            _i7.ResultPattern<_i11.DeletedTaskModel, _i9.TaskException>
          >(this, Invocation.method(#deleteTask, [id])),
        ),
  ) as _i4.Future<_i7.ResultPattern<_i11.DeletedTaskModel, _i9.TaskException>>);
}

/// A class which mocks [TaskViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskViewModel extends _i1.Mock implements _i12.TaskViewModel {
  MockTaskViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TaskScreenState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _FakeTaskScreenState_0(this, Invocation.getter(#state)),
  ) as _i2.TaskScreenState);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> getAllTasks() => (super.noSuchMethod(
    Invocation.method(#getAllTasks, []),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> createTask({
    required String? title,
    required String? content,
  }) => (super.noSuchMethod(
    Invocation.method(#createTask, [], {#title: title, #content: content}),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateTask({
    required int? id,
    required String? title,
    required String? content,
    required bool? isCompleted,
  }) => (super.noSuchMethod(
    Invocation.method(#updateTask, [], {
      #id: id,
      #title: title,
      #content: content,
      #isCompleted: isCompleted,
    }),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTask(int? id) => (super.noSuchMethod(
    Invocation.method(#deleteTask, [id]),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  void resetMutationState() => super.noSuchMethod(
    Invocation.method(#resetMutationState, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetDeletedTaskState() => super.noSuchMethod(
    Invocation.method(#resetDeletedTaskState, []),
    returnValueForMissingStub: null,
  );

  @override
  _i2.TaskScreenState build() => (super.noSuchMethod(
    Invocation.method(#build, []),
    returnValue: _FakeTaskScreenState_0(this, Invocation.method(#build, [])),
  ) as _i2.TaskScreenState);

  @override
  void emitState(_i2.TaskScreenState? newState) => super.noSuchMethod(
    Invocation.method(#emitState, [newState]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
